repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: run-pytest
        name: Run pytest before commit
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        args: [backend]
