services:
  backend_database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
  backend_app:
    image: backend
    entrypoint: ./entrypoint.sh
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@backend_database:5432/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - backend_database
