name: Pipeline
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files from repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        working-directory: backend
        run: poetry install

      - name: Run tests
        working-directory: backend
        run: poetry run pytest
